language: go
go:
  - '1.12'
install:
  - go get github.com/onsi/ginkgo/ginkgo
  - go get github.com/onsi/gomega
  - export GO111MODULE=on
script:
  - |
    if [ "$(go fmt ./...)"]; then
      echo "You need to run `go fmt`"
      exit 1
    fi
  - go test ./... -v
after_success:
  - bin/build-all.sh
deploy:
  provider: releases
  api_key:
    secure: HdGUF67cuTV3FSrIRR2qb2orrxBkt1i3IFxf1ch0fxPK+uQkWi759uOO0GLYAquBQEShSFLtzm34/iEgyP1Z/0j9UelqSw2arUCI8lNxycjMUKLVT0sf4eFJaeu2o2sDb0tkvpFClqLWn2Otm8Sx6ED6XOmqnJo3rErol1fTDo3RaHhkOd1ZsrvDl/lzd29upDSAnTcWHnNLoctvAAYSTItPsoUJJb/gTOjkUTKsbCr7enknZcO0D6kTTUtKmYmGRkWNPSOPTJCfmjfNkWA+sdCE6WS2vCLVPPhpdfNUOGtFeardqC2QWPZMMHSCD52NDXuG8vk3IHi7wHNx1eq4CVhggd13tsk1s1ezEieSRSS8PLica9yQGJufZRkCA1OLJanUJcXDBuFkfMfGpd33OdaZaOqSZasEHwdk/YYfzMd6NcjUoz1KIjEvDWXODfv2NugX7cELtAC8SYvu/uVVJ1MF5NER5+oNZFgII2bo1nFbsjTIJuUlLVy2bxdipCvibcZGjcIbtO8853zaNfhiKVPDeCglCXrWpniInCQB9l/ubVqZ7t8vN7Tk76gHEk8DqocEx+/9pNN1r9XsnX1nIq3K99ccFUKGQHZl1gvhVCHzSmvr//KcgSxKdi/EVxyHklzs5j5jPSMT/s9q3bYprH5s89NjGvNwKwYsnWYossI=
  file:
    - out/socks5-nameserver_darwin_amd64
    - out/socks5-nameserver_linux_amd64
    - out/socks5-nameserver_windows_amd64.exe
    - out/socks5-nameserver_darwin_amd64.zip
    - out/socks5-nameserver_linux_amd64.zip
    - out/socks5-nameserver_windows_amd64.zip
    - out/sha256.txt
  on:
    tags: true
    all_branches: true
  skip_cleanup: true
